version: "3.8"

services:
  backend:
    build:
      context: https://github.com/superboyAmira/web-back.git#main
      dockerfile: Dockerfile
    image: tournament-backend:latest
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: https://github.com/superboyAmira/web-kursovaya-2025.git#main
      dockerfile: Dockerfile
    image: chess-tournament-ui:latest
    command: ["npm","run","preview"]
    ports:
      - "4173:4173"
    depends_on:
      - backend
    restart: unless-stopped
