version: "3.8"

services:
  backend:
    build:
      context: https://github.com/superboyAmira/web-back.git#main
      dockerfile: Dockerfile
    image: your-org/tournament-backend:latest
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: https://github.com/superboyAmira/web-kursovaya-2025.git#main
      dockerfile: Dockerfile
    image: your-org/chess-tournament-ui:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
